import { createRequire } from 'node:module';
import { mkdir, readFile } from 'node:fs/promises';
import { resolve, sep } from 'node:path';
import { createServer } from 'node:http';
import assert from 'node:assert/strict';

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const output = resolve('../outputs/react-qa');
await mkdir(output, { recursive: true });
const server = process.env.WEBSITE_URL ? null : createServer(async (req, res) => {
  try {
    const path = new URL(req.url, 'http://localhost').pathname.replace(/^\/daily-updates\//, '');
    const file = resolve('dist', path || 'index.html');
    if (!file.startsWith(resolve('dist') + sep)) { res.writeHead(403); return res.end(); }
    const body = await readFile(file);
    const extension = file.split('.').pop();
    const types = { html: 'text/html', js: 'text/javascript', css: 'text/css', svg: 'image/svg+xml' };
    res.writeHead(200, { 'Content-Type': types[extension] || 'application/octet-stream' }); res.end(body);
  } catch { res.writeHead(404); res.end(); }
});
if (server) await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const websiteUrl = process.env.WEBSITE_URL || `http://127.0.0.1:${server.address().port}/daily-updates/`;
let browser;
try {
  browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_EXECUTABLE ? { executablePath: process.env.BROWSER_EXECUTABLE } : {}) });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
  const page = await context.newPage();
  page.setDefaultTimeout(10000);
  const errors = [];
  page.on('pageerror', err => errors.push(err.message));
  await page.goto(websiteUrl);
  await page.getByRole('heading', { name: 'Daily Updates', exact: true }).waitFor();
  assert.equal(await page.locator('.brand img').evaluate(img => img.complete && img.naturalWidth > 0), true);
  await page.screenshot({ path: resolve(output, 'desktop-empty.png'), fullPage: true });
  await page.getByRole('button', { name: 'Load sample updates' }).click();
  await page.getByText('5 records', { exact: true }).waitFor();
  await page.getByRole('status').waitFor({ state: 'hidden' });
  await page.screenshot({ path: resolve(output, 'desktop.png'), fullPage: true });
  await page.getByRole('button', { name: 'Your profile', exact: true }).click();
  await page.getByLabel('Your name', { exact: true }).fill('Jordan Tester');
  await page.getByLabel('Department (optional)', { exact: true }).fill('Validation');
  await page.getByRole('button', { name: 'Save profile' }).click();
  await page.getByRole('button', { name: 'Add update', exact: true }).click();
  await page.getByLabel('Feature / module', { exact: true }).fill('Browser validation');
  await page.getByLabel('Ticket number', { exact: true }).fill('APP-9001');
  await page.getByLabel('Description', { exact: true }).fill('<img src=x onerror=alert(1)> stays plain text');
  await page.getByLabel('Hours', { exact: true }).fill('2');
  await page.getByLabel('ETA has changed', { exact: true }).check();
  await page.getByRole('button', { name: 'Save update', exact: true }).click();
  assert.equal(await page.getByLabel('Reason for ETA change', { exact: true }).evaluate(el => el.validity.valueMissing), true);
  await page.getByLabel('Reason for ETA change', { exact: true }).fill('Additional validation');
  await page.getByRole('button', { name: 'Save update', exact: true }).click();
  await page.getByText('6 records', { exact: true }).waitFor();
  await page.reload();
  await page.getByText('APP-9001', { exact: true }).waitFor();
  console.log('PASS: create, ETA validation and reload persistence');
  await page.getByRole('link', { name: 'My updates', exact: true }).click();
  await page.getByText('1 records', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Edit APP-9001', exact: true }).click();
  await page.getByLabel('Status', { exact: true }).selectOption('Done');
  await page.getByRole('button', { name: 'Save update', exact: true }).click();
  assert.equal(await page.locator('tbody .status-badge').innerText(), 'Done');
  await page.getByRole('button', { name: 'View APP-9001', exact: true }).click();
  await page.getByText('<img src=x onerror=alert(1)> stays plain text', { exact: true }).last().waitFor();
  assert.equal(await page.locator('dialog img').count(), 0);
  await page.getByRole('button', { name: 'Close', exact: true }).last().click();
  const csvDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export visible updates as CSV' }).click();
  const csv = await csvDownload; await csv.saveAs(resolve(output, 'filtered.csv'));
  assert.ok((await readFile(resolve(output, 'filtered.csv'), 'utf8')).includes('APP-9001'));
  assert.ok(!(await readFile(resolve(output, 'filtered.csv'), 'utf8')).includes('APP-104'));
  const backupDownload = page.waitForEvent('download'); await page.getByRole('button', { name: 'Backup', exact: true }).click();
  await (await backupDownload).saveAs(resolve(output, 'backup.json'));
  const backup = await readFile(resolve(output, 'backup.json'));
  await page.getByRole('button', { name: 'Delete APP-9001', exact: true }).click();
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByText('APP-9001', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Delete APP-9001', exact: true }).click();
  await page.getByRole('button', { name: 'Delete update', exact: true }).click();
  assert.equal(await page.locator('tbody tr').count(), 0);
  await page.getByLabel('Import backup file').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: backup });
  await page.getByRole('button', { name: 'Restore backup', exact: true }).click();
  await page.getByText('APP-9001', { exact: true }).waitFor();
  await page.getByLabel('Import backup file').setInputFiles({ name: 'broken.json', mimeType: 'application/json', buffer: Buffer.from('{broken') });
  console.log('PASS: edit, details, delete and backup restore');
  await page.getByText('The selected file is not valid JSON.', { exact: true }).waitFor();
  await page.getByRole('link', { name: 'All updates', exact: true }).click();
  await page.locator('.filter-field select').selectOption('Blocked');
  assert.equal(await page.locator('tbody tr').count(), 1);
  await page.locator('.filter-field select').selectOption('');
  await page.getByLabel('Search updates', { exact: true }).fill('APP-108');
  assert.equal(await page.locator('tbody tr').count(), 1);
  await page.getByLabel('Search updates', { exact: true }).fill('');
  const second = await context.newPage(); await second.goto(websiteUrl);
  await second.getByRole('button', { name: 'Your profile', exact: true }).click();
  await second.getByLabel('Your name', { exact: true }).fill('Second tab');
  await second.getByRole('button', { name: 'Save profile' }).click();
  await page.locator('.profile-copy strong').filter({ hasText: 'Second tab' }).waitFor();
  await second.close();
  await page.getByRole('link', { name: 'People', exact: true }).click();
  assert.equal(await page.locator('.person-item').count(), 4);
  await page.getByRole('link', { name: 'All updates', exact: true }).click();
  await page.getByRole('status').waitFor({ state: 'hidden' });
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `No horizontal overflow at ${width}px`);
    await page.screenshot({ path: resolve(output, `mobile-${width}.png`), fullPage: true });
    await page.getByRole('button', { name: 'Add update', exact: true }).click();
    await page.getByLabel('Feature / module', { exact: true }).waitFor();
    await page.locator('dialog').evaluate(async el => { await Promise.all(el.getAnimations().map(animation => animation.finished.catch(() => {}))); });
    assert.equal(await page.locator('dialog').evaluate(el => el.getBoundingClientRect().right <= innerWidth && el.getBoundingClientRect().left >= 0), true);
    await page.screenshot({ path: resolve(output, `mobile-editor-${width}.png`) });
    await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  }
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new Error('QuotaExceededError'); }; });
  await page.getByRole('button', { name: 'Your profile', exact: true }).click();
  await page.getByLabel('Your name', { exact: true }).fill('Must not persist');
  await page.getByRole('button', { name: 'Save profile', exact: true }).click();
  await page.locator('dialog [role="alert"]').filter({ hasText: 'Could not save' }).waitFor();
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  assert.equal(await page.locator('.profile-copy strong').innerText(), 'Second tab');
  await page.reload();
  assert.equal(await page.locator('.profile-copy strong').innerText(), 'Second tab');
  await page.evaluate(() => localStorage.setItem('daily-updates-react-v1', '{corrupt'));
  await page.reload();
  await page.getByRole('alert').filter({ hasText: 'Saved data could not be read' }).waitFor();
  assert.equal(await page.evaluate(() => localStorage.getItem('daily-updates-react-v1')), '{corrupt');
  assert.deepEqual(errors, []);
  console.log('PASS: create, validation, edit, delete/cancel, reload, filtering, details, CSV, backups, cross-tab sync, storage failures, desktop/mobile layouts; no browser exceptions.');
  await context.close();
} finally { await browser?.close(); if (server) await new Promise(resolve => server.close(resolve)); }
