import { createRequire } from 'node:module';
import { mkdir, readFile } from 'node:fs/promises';
import { resolve, sep } from 'node:path';
import { createServer } from 'node:http';
import assert from 'node:assert/strict';

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const output = resolve('../outputs/react-qa');
await mkdir(output, { recursive: true });
const server = process.env.WEBSITE_URL ? null : createServer(async (req, res) => {
  try {
    const path = new URL(req.url, 'http://localhost').pathname.replace(/^\/daily-updates\//, '');
    const file = resolve('dist', path || 'index.html');
    if (!file.startsWith(resolve('dist') + sep)) { res.writeHead(403); return res.end(); }
    const body = await readFile(file);
    const extension = file.split('.').pop();
    const types = { html: 'text/html', js: 'text/javascript', css: 'text/css', svg: 'image/svg+xml' };
    res.writeHead(200, { 'Content-Type': types[extension] || 'application/octet-stream' }); res.end(body);
  } catch { res.writeHead(404); res.end(); }
});
if (server) await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const websiteUrl = process.env.WEBSITE_URL || `http://127.0.0.1:${server.address().port}/daily-updates/`;
let browser;
try {
  browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_EXECUTABLE ? { executablePath: process.env.BROWSER_EXECUTABLE } : {}) });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
  const page = await context.newPage();
  page.setDefaultTimeout(10000);
  const errors = [];
  page.on('pageerror', err => errors.push(err.message));
  const nav = name => page.getByRole('navigation', { name: 'Main navigation' }).getByRole('link', { name, exact: true });
  const records = page.locator('.update-record');
  await page.goto(websiteUrl);
  await page.getByRole('heading', { name: 'Welcome to Daily Updates App', exact: true }).waitFor();
  assert.equal(await page.locator('.application-brand img').evaluate(img => img.complete && img.naturalWidth > 0), true);
  await page.screenshot({ path: resolve(output, 'application-empty.png'), fullPage: true });
  await page.getByRole('button', { name: 'Load sample updates' }).click();
  await page.getByText('5 updates', { exact: true }).waitFor();
  await page.getByRole('status').waitFor({ state: 'hidden' });
  await page.screenshot({ path: resolve(output, 'application-home.png'), fullPage: true });
  await page.getByRole('link', { name: 'Maya Patel', exact: true }).click();
  await page.getByRole('heading', { name: 'Updates for Maya Patel' }).waitFor();
  assert.equal(await records.count(), 2);
  await page.getByRole('button', { name: 'Your profile', exact: true }).click();
  await page.getByLabel('Your name', { exact: true }).fill('Jordan Tester');
  await page.getByLabel('Department (optional)', { exact: true }).fill('Validation');
  await page.getByRole('button', { name: 'Save profile' }).click();
  await nav('Add Update').click();
  await page.getByLabel('Feature/Module', { exact: true }).fill('Browser validation');
  await page.getByLabel('Ticket Number', { exact: true }).fill('APP-9001');
  await page.getByLabel('Ticket Description', { exact: true }).fill('<img src=x onerror=alert(1)> stays plain text');
  await page.getByLabel('Status', { exact: true }).selectOption('In Progress');
  await page.getByLabel('Hours', { exact: true }).fill('2');
  await page.getByLabel('Has ETA Changed?', { exact: true }).check();
  await page.getByRole('button', { name: 'Save Update', exact: true }).click();
  assert.equal(await page.getByLabel('ETA Change Description', { exact: true }).evaluate(el => el.validity.valueMissing), true);
  await page.getByLabel('ETA Change Description', { exact: true }).fill('Additional validation');
  await page.screenshot({ path: resolve(output, 'application-add.png'), fullPage: true });
  await page.getByRole('button', { name: 'Save Update', exact: true }).click();
  await page.getByRole('heading', { name: 'My Daily Updates' }).waitFor();
  assert.equal(await records.count(), 1);
  await page.reload();
  await page.getByText('APP-9001', { exact: true }).waitFor();
  await records.getByRole('link', { name: 'Edit', exact: true }).click();
  await page.getByRole('heading', { name: 'Edit Daily Update' }).waitFor();
  await page.getByLabel('Status', { exact: true }).selectOption('Done');
  await page.getByRole('button', { name: 'Save Changes', exact: true }).click();
  assert.equal(await records.locator('.status-badge').innerText(), 'Done');
  await page.screenshot({ path: resolve(output, 'application-mine.png'), fullPage: true });
  await records.getByRole('link', { name: 'View Details', exact: true }).click();
  await page.getByRole('heading', { name: 'Update Details' }).waitFor();
  assert.equal(await page.locator('.details-page img').count(), 0);
  await page.getByText('<img src=x onerror=alert(1)> stays plain text', { exact: true }).waitFor();
  await page.getByRole('link', { name: 'Back to My Updates', exact: true }).first().click();
  const csvDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export visible updates as CSV' }).click();
  await (await csvDownload).saveAs(resolve(output, 'filtered.csv'));
  const csv = await readFile(resolve(output, 'filtered.csv'), 'utf8');
  assert.ok(csv.includes('APP-9001') && !csv.includes('APP-104'));
  const backupDownload = page.waitForEvent('download'); await page.getByRole('button', { name: 'Backup', exact: true }).click();
  await (await backupDownload).saveAs(resolve(output, 'backup.json'));
  const backup = await readFile(resolve(output, 'backup.json'));
  await page.getByRole('button', { name: 'Delete APP-9001', exact: true }).click();
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByText('APP-9001', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Delete APP-9001', exact: true }).click();
  await page.getByRole('button', { name: 'Delete update', exact: true }).click();
  assert.equal(await records.count(), 0);
  await page.getByLabel('Import backup file').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: backup });
  await page.getByRole('button', { name: 'Restore backup', exact: true }).click();
  await page.getByText('APP-9001', { exact: true }).waitFor();
  await page.getByLabel('Import backup file').setInputFiles({ name: 'broken.json', mimeType: 'application/json', buffer: Buffer.from('{broken') });
  await page.getByText('The selected file is not valid JSON.', { exact: true }).waitFor();
  console.log('PASS: employee page, full-page create/edit/details, validation, persistence, delete/cancel, CSV and backups');
  await nav('Team Dashboard').click();
  assert.equal(await records.count(), 6);
  assert.deepEqual(await page.locator('.application-stat strong').allTextContents(), ['6', '1', '1', '2']);
  await page.getByLabel('Filter by status').selectOption('Blocked');
  assert.equal(await records.count(), 1);
  await page.getByLabel('Filter by status').selectOption('');
  await page.getByLabel('Search updates', { exact: true }).fill('APP-108');
  assert.equal(await records.count(), 1);
  await page.getByLabel('Search updates', { exact: true }).fill('');
  await page.screenshot({ path: resolve(output, 'application-team.png'), fullPage: true });
  await nav('Add Update').click();
  await page.getByLabel('Feature/Module', { exact: true }).fill('Unsaved');
  await page.getByLabel('Has ETA Changed?', { exact: true }).check();
  await page.getByRole('button', { name: 'Clear Form' }).click();
  assert.equal(await page.getByLabel('Feature/Module', { exact: true }).inputValue(), '');
  assert.equal(await page.getByLabel('Has ETA Changed?', { exact: true }).isChecked(), false);
  const second = await context.newPage(); await second.goto(websiteUrl);
  await second.getByRole('button', { name: 'Your profile', exact: true }).click();
  await second.getByLabel('Your name', { exact: true }).fill('Second tab');
  await second.getByRole('button', { name: 'Save profile' }).click();
  await page.getByRole('heading', { name: 'Welcome to Daily Updates App', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Your profile' }).filter({ hasText: 'Second tab' }).waitFor();
  await second.close();
  await page.getByRole('status').waitFor({ state: 'hidden' });
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 });
    for (const name of ['Home', 'Team Dashboard', 'Add Update']) {
      await nav(name).click();
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `${name}: no overflow at ${width}px`);
      await page.screenshot({ path: resolve(output, `application-${name.replaceAll(' ', '-').toLowerCase()}-${width}.png`), fullPage: true });
    }
  }
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('link', { name: 'Register', exact: true }).click();
  await page.getByLabel('Your name', { exact: true }).fill('Local Account');
  await page.getByLabel('Department (optional)', { exact: true }).fill('Quality');
  await page.getByLabel('Email Address', { exact: true }).fill('local@example.com');
  await page.getByLabel('Password', { exact: true }).fill('BrowserOnly-2026!');
  await page.getByLabel('Confirm Password', { exact: true }).fill('Different-2026!');
  await page.getByRole('button', { name: 'Create Account', exact: true }).click();
  await page.getByRole('alert').filter({ hasText: 'Passwords do not match' }).waitFor();
  await page.getByLabel('Confirm Password', { exact: true }).fill('BrowserOnly-2026!');
  await page.screenshot({ path: resolve(output, 'application-register.png'), fullPage: true });
  await page.getByRole('button', { name: 'Create Account', exact: true }).click();
  await page.getByRole('button', { name: 'Logout', exact: true }).waitFor();
  assert.ok(!(await page.evaluate(() => localStorage.getItem('daily-updates-local-accounts-v1'))).includes('BrowserOnly-2026!'));
  await page.reload(); await page.getByRole('button', { name: 'Logout', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Logout', exact: true }).click();
  await page.getByRole('heading', { name: 'Welcome Back' }).waitFor();
  await page.getByLabel('Email Address').fill('LOCAL@example.com');
  await page.getByLabel('Password', { exact: true }).fill('wrong-password');
  await page.getByRole('button', { name: 'Log In', exact: true }).click();
  await page.getByRole('alert').filter({ hasText: 'Invalid email or password' }).waitFor();
  await page.getByLabel('Password', { exact: true }).fill('BrowserOnly-2026!');
  await page.getByRole('button', { name: 'Show password', exact: true }).click();
  assert.equal(await page.getByLabel('Password', { exact: true }).getAttribute('type'), 'text');
  await page.getByRole('button', { name: 'Hide password', exact: true }).click();
  await page.screenshot({ path: resolve(output, 'application-login.png'), fullPage: true });
  await page.getByRole('button', { name: 'Log In', exact: true }).click();
  await page.getByRole('button', { name: 'Logout', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Logout', exact: true }).click();
  await page.getByRole('link', { name: 'Register', exact: true }).click();
  await page.getByLabel('Your name').fill('Duplicate'); await page.getByLabel('Email Address').fill('local@example.com');
  await page.getByLabel('Password', { exact: true }).fill('BrowserOnly-2026!'); await page.getByLabel('Confirm Password', { exact: true }).fill('BrowserOnly-2026!');
  await page.getByRole('button', { name: 'Create Account', exact: true }).click();
  await page.getByRole('alert').filter({ hasText: 'already registered' }).waitFor();
  await page.getByRole('status').waitFor({ state: 'hidden' });
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `Register: no overflow at ${width}px`);
    await page.screenshot({ path: resolve(output, `application-register-${width}.png`), fullPage: true });
  }
  console.log('PASS: local register/login/logout, duplicate accounts, mismatched/wrong passwords, visibility toggle and reload session');
  await nav('Home').click();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: 'Your profile' }).click();
  await page.getByLabel('Your name').fill('Safe profile'); await page.getByRole('button', { name: 'Save profile' }).click();
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new Error('QuotaExceededError'); }; });
  await page.getByRole('button', { name: 'Your profile', exact: true }).click();
  await page.getByLabel('Your name', { exact: true }).fill('Must not persist');
  await page.getByRole('button', { name: 'Save profile', exact: true }).click();
  await page.locator('dialog [role="alert"]').filter({ hasText: 'Could not save' }).waitFor();
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  assert.ok((await page.getByRole('button', { name: 'Your profile' }).innerText()).includes('Safe profile'));
  await page.reload();
  assert.ok((await page.getByRole('button', { name: 'Your profile' }).innerText()).includes('Safe profile'));
  await page.evaluate(() => localStorage.setItem('daily-updates-react-v1', '{corrupt'));
  await page.reload();
  await page.getByRole('alert').filter({ hasText: 'Saved data could not be read' }).waitFor();
  assert.equal(await page.evaluate(() => localStorage.getItem('daily-updates-react-v1')), '{corrupt');
  assert.deepEqual(errors, []);
  console.log('PASS: filtering, cross-tab editor protection, clear form, storage failures and desktop/mobile layouts; no browser exceptions.');
  await context.close();
} finally { await browser?.close(); if (server) await new Promise(resolve => server.close(resolve)); }
